type Product {
  id: ID!
  name: String!
  description: String!
  image: String!
  category: String!
  price: Float!
  availability: Boolean!
  stock: Int!
  publishedBy: User!
  salePrice: String!
  reviews: [ProductReview!]!
  descountPercentage: Int!
  salesCount: Int
}

type ProductReview {
  productId: ID!
  likes: Int!
  classifications: Int!
  comment: String!
  author: User!
}

type Query {
  products(offset: Int, limit: Int): [Product!]!
  getProduct(id: String!): Product!
}

type Mutation {
  createProduct(data: inputProduct!): Product!
  updateProduct(id: String!, data: inputProduct!): Product!
  createReview(data: inputProductReview!): ProductReview!
  deleteProduct(id: String!): Boolean!
}

input inputUpdateProduct {
  name: String!
  image: String!
  category: String!
  price: Float!
  stock: Int!
  availability: Boolean
  salePrice: Float
  salesCount: Int
  descountPercentage: Int
}

input inputProductReview {
  productId: String!
  author: String!
  comment: String!
  classifications: Int!
  likes: Int!
}

input inputProduct {
  name: String!
  description: String!
  image: String
  category: String!
  price: Float!
  publishedBy: String!
  stock: Int!
}
