type Product {
  id: ID!
  name: String!
  description: String!
  image: String!
  category: String!
  price: Float!
  availability: Boolean!
  stock: Int!
  publishedBy: User!
  salePrice: String!
  productReviews: [ProductReview!]!
  descountPercentage: Int!
  salesCount: Int
}

type ProductReview {
  productId: ID!
  likes: Int!
  classifications: Int!
  comment: String!
  author: User!
}

type Query {
  products(offset: Int, limit: Int): [Product!]!
  getProduct(id: String!): Product!
}

type Mutation {
  createProduct(data: inputProduct): Product!
  updateProduct(id: String!): Product!
  deleteProduct(id: String!): Boolean!
}

input inputProduct {
  name: String!
  description: String!
  image: String
  category: String!
  price: Float!
  publishedBy: String!
  stock: Int!
}
