type Product {
  id: ID!
  name: String!
  description: String!
  images: [ProductImages!]!
  category: String!
  price: Float!
  availability: Boolean!
  stock: Int!
  publishedBy: User!
  salePrice: String!
  reviews: [ProductReview!]!
  descountPercentage: Int!
  salesCount: Int
  emphasis: Boolean
}

type ProductReview {
  productId: ID!
  likes: Int!
  classifications: Int!
  comment: String!
  author: User!
}

type ProductImages {
  desktop: String!
  mobile: String
  tablet: String
}

type Query {
  products: [Product!]!
  getProduct(id: String!): Product!
}

type Mutation {
  createProduct(data: inputProduct!): Product!
  updateProduct(id: String!, data: inputProduct!): Product!
  createReview(data: inputProductReview!): ProductReview!
  deleteProduct(id: String!): Boolean!
}

input inputUpdateProduct {
  name: String!
  images: [inputImages]!
  category: String!
  price: Float!
  stock: Int!
  availability: Boolean
  salePrice: Float
  salesCount: Int
  descountPercentage: Int
}

input inputProductReview {
  productId: String!
  author: String!
  comment: String!
  classifications: Int!
  likes: Int!
}

input inputImages {
  desktop: String!
  mobile: String
  tablet: String
}

input inputProduct {
  name: String!
  description: String!
  images: [inputImages!]!
  category: String!
  price: Float!
  publishedBy: String!
  stock: Int!
}
