type Query {
  login(data: inputLogin): Login!
  getSession(data: inputGetSession): User!
}

type Login {
  token: String!
}

input inputGetSession {
  token: String!
}

input inputLogin {
  email: String!
  password: String!
}
